version: '3'
services:
    verdaccio:
        image: verdaccio/verdaccio:5.7.0
        container_name: verdaccio
        networks:
            - verdaccio
        ports:
            - 4873:4873
        environment:
            - VERDACCIO_APPDIR=/opt/verdaccio
            - VERDACCIO_USER_NAME=verdaccio
            - VERDACCIO_USER_UID=10001
            - VERDACCIO_PORT=4873
            - VERDACCIO_PROTOCOL=http
        volumes:
            - ./conf:/verdaccio/conf
            - verdaccio:/verdaccio/storage
            - ./plugins:/verdaccio/plugins
volumes:
    verdaccio:
        driver: local
networks:
    verdaccio:
        driver: bridge
